spring:
  datasource:
    url: jdbc:mysql://dev-febnine.c3bkd5wqzspw.ap-northeast-2.rds.amazonaws.com:3306/Febnine  # db url
    driver-class-name: com.mysql.cj.jdbc.Driver   # mysql driver
    username: febnine   # host name
    password: 1f9s*aW#01
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create    # Transaction 마다 기존 테이블 삭제 후 다시 생성
    properties:
      hibernate:
        format_sql: true #To beautify or pretty print the SQL
        show_sql: true #show sql


logging.level:
  org.hibernate.type: trace